### ISSUE TITLE
Options system

### ISSUE THREAD

**Issue by Xesau** [Cubition/Cubition#21]
How are we going to do options?
Surely we want it to be modular, say, mods can store their options as well. They can do this themselves, but how are they going to register it to the options manager in the game?

I thought of several ways:
- Just manually adding an action to the OptionsView (which still has to come...)
- Using some sort of collective options manager that every mod registers their options into:
  OptionsManager.registerOptionSet (Mod mod, OptionSet options);
  (OptionSet would be a set of options, each having their own type (number, bool, enum) and a name)

Which one do you like and how would you implement them?

**Comment by ghost** [comment]
Well I feel like mods may want to choose where a button, etc is located on the screen..

**Comment by Xesau** [comment]
Hmm, that's a good one.
Then it's still more complex for the mod to do the things, though.

**Comment by ghost** [comment]
And really complex for them to manage working with other mods

**Comment by Xesau** [comment]
@nverdierDev What do you mean? I think I didn't formulate my message that well.
I meant that it's more difficult for mods to hook into the OptionsView, adding a button which links to yet another view, than just work with a built-in option manager, like the newest Forge experiments with

**Comment by ghost** [comment]
Well if a mod wants a button in a certain place on the screen it would be complicated to manage that with other mods

**Comment by Xesau** [comment]
@nverdierDrv We're talking about the options. I understand that for some things, but options...

**Comment by ghost** [comment]
Ah I see. Well the second one seems more suitable IMO.
